sonar.projectKey=php-injector
sonar.projectName=php-injector
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.exclusions=vendor/**,build/**
sonar.coverage.exclusions=tests/**,vendor/**,build/**

sonar.php.coverage.reportPaths=build/test-results/clover.xml
sonar.php.tests.reportPath=build/test-results/junit.xml
